<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite41b716bf1cc223252fb1afb8956d63f
{
    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'setasign\\Fpdi\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'setasign\\Fpdi\\' => 
        array (
            0 => __DIR__ . '/..' . '/setasign/fpdi/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'FormFiller' => 
            array (
                0 => __DIR__ . '/..' . '/ghostfly/pdf-forms-filler/src',
            ),
        ),
    );

    public static $classMap = array (
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite41b716bf1cc223252fb1afb8956d63f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite41b716bf1cc223252fb1afb8956d63f::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInite41b716bf1cc223252fb1afb8956d63f::$prefixesPsr0;
            $loader->classMap = ComposerStaticInite41b716bf1cc223252fb1afb8956d63f::$classMap;

        }, null, ClassLoader::class);
    }
}
