<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'FormFiller' => array($vendorDir . '/ghostfly/pdf-forms-filler/src'),
);
